# Copyright 2025 Vinicius Fortuna
# SPDX-License-Identifier: Apache-2.0

# Run this firmware on the development machine for more convenient LVGL development.

esphome:
  name: sdl
  on_boot: 
    then:
      - lvgl.label.update:
          id: title_label
          text: Title
      - lvgl.label.update:
          id: subtitle_label
          text: Subtitle

host:

logger:
  level: VERBOSE

packages:
  base: !include ./lvgl.yaml

text:
  - id: badge_title
    name: Badge Title
    platform: lvgl
    widget: title_label
    mode: text

  - id: badge_subtitle
    name: Badge Subtitle
    platform: lvgl
    widget: subtitle_label
    mode: text

  - name: QR Code Text
    initial_value: https://example.com
    platform: template
    icon: mdi:qrcode
    optimistic: true
    mode: text
    update_interval: never
    restore_value: true
    on_value:
      - lvgl.qrcode.update:
          id: qr_code_image
          text: !lambda return x;
      - if:
          condition: {lambda: return x.length() > 0;}
          then:
            - lvgl.widget.show: qr_code_image
            - lvgl.widget.hide: empty_qr_code_label
          else:
            - lvgl.widget.hide: qr_code_image
            - lvgl.widget.show: empty_qr_code_label

binary_sensor:
  - { id: button_1,   platform: sdl, sdl_id: badge_display, key: SDLK_m}
  - { id: button_2,   platform: sdl, sdl_id: badge_display, key: SDLK_COMMA }
  - { id: button_3,   platform: sdl, sdl_id: badge_display, key: SDLK_PERIOD }
  - { id: button_4, platform: sdl, sdl_id: badge_display, key: SDLK_SLASH }
  - { id: key_up,     platform: sdl, sdl_id: badge_display, key: SDLK_u }
  - { id: key_down,   platform: sdl, sdl_id: badge_display, key: SDLK_d }
  - { id: key_left,   platform: sdl, sdl_id: badge_display, key: SDLK_LEFTBRACKET }
  - { id: key_right,  platform: sdl, sdl_id: badge_display, key: SDLK_RIGHTBRACKET }

display:
  - id: badge_display
    platform: sdl
    dimensions: {width: 320, height: 240}
    auto_clear_enabled: false
    update_interval: never
