# Copyright 2025 Vinicius Fortuna
# SPDX-License-Identifier: Apache-2.0

packages:
  # These must be in reverse order, as they get prepended to the pages list.
  #   wifi: !include page_wifi.yaml
  ir_blast: !include page_ir_blast.yaml
  qr: !include page_qr.yaml
  air: !include page_air.yaml
  badge: !include page_badge.yaml

font:
  - file: "gfonts://Material+Symbols+Rounded"
    id: icons_50
    size: 50
    glyphs: [
      "\U0000ea67",  # badge
      "\U0000e29c",  # airwave
      "\U0000e00a",  # qr_code_2
      "\U0000f747",  # laser-pointer
      "\U0000e63e",  # wifi
    ]

lvgl:
  - id: badge_lvgl
    log_level: DEBUG
    displays: [badge_display]
    # Need to reduce due to lack of PSRAM, as per https://esphome.io/components/lvgl/.
    buffer_size: 25%

    # encoders:
    #   - enter_button: key_select
    #     sensor:
    #       left_button: key_prev
    #       right_button: key_next

    keypads:
      - id: lvgl_keypad
        long_press_repeat_time: 65535ms
        # esc: button_1
        prev: button_2
        next: button_3
        enter: button_4
        # up: key_up
        # down: key_down
        # left: key_left
        # right: key_right

    # theme:
    #   obj:
    #     styles: [debug_border]

    style_definitions:
      - id: container
        radius: 0
        pad_all: 0
        border_width: 0
        bg_opa: 0%

      - id: debug_border
        border_width: 1
        border_color: 0xFFFF00

      - id: page
        width: 100%
        height: 100%

      - id: surface
        bg_color: 0xFFFFFF
        bg_opa: 100%

      - id: switcher_entry
        radius: 0
        pad_all: 0
        border_width: 0
        bg_opa: 0%
        text_color: 0xFFFFFF
        width: SIZE_CONTENT
        height: SIZE_CONTENT

      - id: switcher_button
        width: SIZE_CONTENT
        height: SIZE_CONTENT
        bg_opa: 0%
        shadow_width: 0
        shadow_opa: 0%
        text_font: icons_50
        radius: 8

      - id: switcher_focused
        bg_opa: 70%
        bg_color: 0x000000
        outline_width: 0
        outline_opa: 0%
        outline_pad: 0

    # Style for the root screen.
    height: 100%
    width: 100%

    top_layer:
      widgets:
        - !include ./page_selector.yaml

    pages:

binary_sensor:
  - id: !extend button_1
    on_press:
      - script.execute: show_selector
    on_release:
      - script.execute: dismiss_selector

script:
  - id: show_selector
    then:
      - lambda: |-
          lv_obj_clear_flag(id(page_selector), LV_OBJ_FLAG_HIDDEN);
          lv_group_t* selector_group = (lv_group_t*) lv_obj_get_user_data(id(page_selector));
          ESP_LOGD("lvgl", "selector group: %p", selector_group);

          // Focus on the current page in the selector group.
          ESP_LOGD("lvgl", "current page: %zu", id(badge_lvgl).get_current_page());
          auto obj_to_focus = get_group_item_by_index(selector_group, id(badge_lvgl).get_current_page());
          lv_group_focus_obj(obj_to_focus);

          // Make keypad feed into the selector group.
          lv_indev_t* indev = find_indev_by_driver(id(lvgl_keypad).get_drv());
          ESP_LOGD("lvgl", "setting indev %p to group %p", indev, selector_group);
          lv_indev_set_group(indev, selector_group);

  - id: dismiss_selector
    then:
      - lambda: |-
          lv_group_t* selector_group = (lv_group_t*) lv_obj_get_user_data(id(page_selector));
          auto page_index = get_focused_item_index_in_group(selector_group);
          lv_obj_add_flag(id(page_selector), LV_OBJ_FLAG_HIDDEN);
          id(badge_lvgl).show_page(page_index, LV_SCR_LOAD_ANIM_FADE_OUT, 50);
          lv_group_t* page_group = (lv_group_t*) lv_obj_get_user_data(lv_scr_act());
          lv_indev_t* indev = find_indev_by_driver(id(lvgl_keypad).get_drv());
          ESP_LOGD("lvgl", "setting indev %p to group %p", indev, page_group);
          lv_indev_set_group(indev, page_group);
          // TODO(fortuna): Focus on the first item in the page.
          lv_group_focus_next(page_group);
          //   auto obj_to_focus = get_group_item_by_index(page_group, 0);
          //   lv_group_focus_obj(obj_to_focus);
