# Copyright 2025 Vinicius Fortuna
# SPDX-License-Identifier: Apache-2.0

# Run this firmware on the development machine for more convenient LVGL development.

packages:
  base: !include ./lvgl.yaml

esphome:
  name: sdl
  includes:
    - menu.h
  on_boot: 
    then:
      # Set mock values
      - text.set:
          id: badge_title
          value: Title
      - text.set:
          id: badge_subtitle
          value: Subtitle
      - script.execute:
          id: badge_on_eco2_value
          x: 4321.0
      - script.execute:
          id: badge_on_tvoc_value
          x: 123.0
      - text.set:
          id: qr_code_text
          value: 'https://example.com'

host:

logger:
  level: VERBOSE

display:
  - id: badge_display
    platform: sdl
    dimensions: {width: 320, height: 240}
    auto_clear_enabled: false
    update_interval: never

binary_sensor:
  - { id: button_1,   platform: sdl, sdl_id: badge_display, key: SDLK_m}
  - { id: button_2,   platform: sdl, sdl_id: badge_display, key: SDLK_COMMA }
  - { id: button_3,   platform: sdl, sdl_id: badge_display, key: SDLK_PERIOD }
  - { id: button_4,   platform: sdl, sdl_id: badge_display, key: SDLK_SLASH }
  - { id: key_up,     platform: sdl, sdl_id: badge_display, key: SDLK_u }
  - { id: key_down,   platform: sdl, sdl_id: badge_display, key: SDLK_d }
  - { id: key_left,   platform: sdl, sdl_id: badge_display, key: SDLK_LEFTBRACKET }
  - { id: key_right,  platform: sdl, sdl_id: badge_display, key: SDLK_RIGHTBRACKET }

script:
  # Provide fake air sensor API.
  - id: badge_on_eco2_value
    parameters:
      x: float  # Value in ppm
    then: []
  - id: badge_on_tvoc_value
    parameters:
      x: float  # Value in ppb
    then: []
  # Sends the Fake IR blast command.
  - id: on_ir_blast_click
    mode: single
    then:
      - logger.log:
          level: DEBUG
          format: "Fake IR blast command sent with address: 0xD880, command: 0xDD"