# Copyright 2025 Vinicius Fortuna
# SPDX-License-Identifier: Apache-2.0

# This file defines the hardware of the Pro version of the badge.

packages:
  # Inherit from the basic model
  hardware: !include ./badge_0.8.13_basic.yaml

spi:
  - id: spi_bus
    clk_pin: GPIO06  # SPI_SCK
    mosi_pin: GPIO07  # SPI_SDO

display:
  - id: badge_display
    platform: ili9xxx
    model: ST7789V
    dc_pin: GPIO00  # TFT_DC
    cs_pin: GPIO04  # SPI_CS1
    reset_pin: GPIO01  # SPI_CS2
    invert_colors: true
    # We need PSRAM to use 16 bit, so we reduce the color bit depth.
    color_palette: 8BIT
    dimensions:
      width: 320
      height: 240
    transform:
      swap_xy: true
      mirror_y: true

sensor:
  - platform: max17043  # U4
    id: battery_sensor
    i2c_id: badge_i2c
    address: 0x36
    battery_voltage: {name: Battery Voltage}
    battery_level: {name: Battery Level}

  - platform: sgp30  # U7
    id: air_sensor
    i2c_id: badge_i2c
    address: 0x58
    # See https://esphome.io/components/sensor/sgp30.html#calibrating-baseline.
    # These are values I've observed in my badge after running it for 17 hours.
    baseline:
      eco2_baseline: 0x927D
      tvoc_baseline: 0x9853
    store_baseline: true
    # Estimated CO₂ concentration ("CO₂ equivalent")
    eco2:
      name: CO₂eq
      on_value:
        - script.execute:
            id: badge_on_eco2_value
            x: !lambda return x;
    # Total Volatile Organic Compounds
    tvoc:
      name: TVOC
      on_value:
        - script.execute:
            id: badge_on_tvoc_value
            x: !lambda 'return x;'
    # Baseline values for calibration
    eco2_baseline: {name: CO₂eq Calibration Baseline}
    tvoc_baseline: {name: TVOC Calibration Baseline}

script:
  # Exposed air sensor API.
  - id: badge_on_eco2_value
    parameters:
      x: float  # Value in ppm
    then: []

  - id: badge_on_tvoc_value
    parameters:
      x: float  # Value in ppb
    then: []
