# Copyright 2025 Vinicius Fortuna
# SPDX-License-Identifier: Apache-2.0

# This is a development version of the firmware that bypasses the USB conflict in
# the deployment version to allow for serial monitoring.

packages:
  base: !include ./main.yaml

esphome:
  name: hope-badge-dev
  friendly_name: HOPE Badge (Dev)
  name_add_mac_suffix: false

wifi:
  # Convenience wifi configuration for development.
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

# Over-the-Air provisioning.
ota:
  - platform: esphome
    password: !secret ota_password
