# Copyright 2025 Vinicius Fortuna
# SPDX-License-Identifier: Apache-2.0

name: Run Tests

on:
  push:
    branches: [main]
    paths:
      - '**.yaml'
  pull_request:
    branches: [main]
    paths:
      - '**.yaml'

jobs:
  compile-demos:
    name: Compile Demos
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Lint YAML
        shell: bash
        run: yamllint **/*.yaml

      - name: Install ESPHome
        run: pip install esphome

      - name: Compile Firmwares
        env:
          PLATFORMIO_BUILD_CACHE_DIR: /tmp/esphome
        shell: bash
        # TODO: Need to install SDL on Linux for Host platform:
        # apt install libsdl2-dev libsodium-dev build-essential git
        run: |
          echo "ap_password: example_password" > secrets.yaml
          echo "ota_password: example_password" >> secrets.yaml
          for config in firmware_screen/main_dev.yaml firmware_no_screen/main_dev.yaml; do
            esphome compile "$config" || {
              echo "ERROR: Compilation failed for $config"
              exit 1
            }
          done
          echo "All found ESPHome demos compiled successfully."
